BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE registros_colheita CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE talhoes CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fazendas CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE fazendas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120 CHAR) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE talhoes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fazenda_id NUMBER NOT NULL,
    codigo VARCHAR2(30 CHAR) NOT NULL,
    nome VARCHAR2(120 CHAR),
    area_hectares NUMBER(10,2) NOT NULL CHECK (area_hectares > 0),
    localizacao_descricao VARCHAR2(255 CHAR),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_talhoes_fazenda
        FOREIGN KEY (fazenda_id) REFERENCES fazendas(id) ON DELETE CASCADE,
    CONSTRAINT uq_talhoes_fazenda_codigo
        UNIQUE (fazenda_id, codigo)
);

CREATE TABLE registros_colheita (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fazenda_id NUMBER NOT NULL,
    talhao_id NUMBER NOT NULL,
    safra VARCHAR2(9 CHAR) NOT NULL,
    data_fechamento DATE NOT NULL,
    tipo_colheita VARCHAR2(20 CHAR) NOT NULL
        CHECK (tipo_colheita IN ('manual', 'semimecanizada', 'mecanizada')),
    producao_prevista_ton NUMBER(12,2) NOT NULL CHECK (producao_prevista_ton > 0),
    producao_real_ton NUMBER(12,2) NOT NULL CHECK (producao_real_ton >= 0),
    perda_ton NUMBER(12,2) NOT NULL CHECK (perda_ton >= 0),
    perda_percentual NUMBER(7,2) NOT NULL CHECK (perda_percentual >= 0),
    equipe_responsavel VARCHAR2(120 CHAR) NOT NULL,
    observacoes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_registros_fazenda
        FOREIGN KEY (fazenda_id) REFERENCES fazendas(id) ON DELETE CASCADE,
    CONSTRAINT fk_registros_talhao
        FOREIGN KEY (talhao_id) REFERENCES talhoes(id) ON DELETE CASCADE,
    CONSTRAINT uq_registros_talhao_safra
        UNIQUE (talhao_id, safra)
);
